//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AD.APP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AD.APP.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accéléromètre X : {0:F3}.
        /// </summary>
        internal static string accelerometerX {
            get {
                return ResourceManager.GetString("accelerometerX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accéléromètre Y : {0:F3}.
        /// </summary>
        internal static string accelerometerY {
            get {
                return ResourceManager.GetString("accelerometerY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accéléromètre Z : {0:F3}.
        /// </summary>
        internal static string accelerometerZ {
            get {
                return ResourceManager.GetString("accelerometerZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude : {0:F2} m.
        /// </summary>
        internal static string altitude {
            get {
                return ResourceManager.GetString("altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude : {0:F2} mètres.
        /// </summary>
        internal static string altitude_accessibility {
            get {
                return ResourceManager.GetString("altitude_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps moyen par cycle : {0:F2} ms.
        /// </summary>
        internal static string averageTime {
            get {
                return ResourceManager.GetString("averageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps moyen écoulé par cycle : {0:F2} millisecondes.
        /// </summary>
        internal static string averageTime_accessibility {
            get {
                return ResourceManager.GetString("averageTime_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau de la batterie : {0:F0}%.
        /// </summary>
        internal static string batteryLevel {
            get {
                return ResourceManager.GetString("batteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niveau de la batterie : {0:F0} pourcent.
        /// </summary>
        internal static string batteryLevel_accessibility {
            get {
                return ResourceManager.GetString("batteryLevel_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vue de la caméra pour la lecture des QR codes.
        /// </summary>
        internal static string cameraView_accessibility {
            get {
                return ResourceManager.GetString("cameraView_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le test CPU est prêt.
        /// </summary>
        internal static string cpuTestReady_accessibility {
            get {
                return ResourceManager.GetString("cpuTestReady_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le test CPU est en cours.
        /// </summary>
        internal static string cpuTestRunning_accessibility {
            get {
                return ResourceManager.GetString("cpuTestRunning_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test CPU.
        /// </summary>
        internal static string cpuTestSection {
            get {
                return ResourceManager.GetString("cpuTestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section concernant les tests CPU.
        /// </summary>
        internal static string cpuTestSection_accessibility {
            get {
                return ResourceManager.GetString("cpuTestSection_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations de l&apos;appareil.
        /// </summary>
        internal static string deviceInfoSection {
            get {
                return ResourceManager.GetString("deviceInfoSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;appareil : {0}.
        /// </summary>
        internal static string deviceName {
            get {
                return ResourceManager.GetString("deviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appareil.
        /// </summary>
        internal static string deviceTitle {
            get {
                return ResourceManager.GetString("deviceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taux de croissance : {0:F4} MB / cycle.
        /// </summary>
        internal static string growthRate {
            get {
                return ResourceManager.GetString("growthRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taux de croissance : {0:F4} mégaoctets par cycle.
        /// </summary>
        internal static string growthRate_accessibility {
            get {
                return ResourceManager.GetString("growthRate_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empreinte structurelle : {0:F4} MB.
        /// </summary>
        internal static string intercept {
            get {
                return ResourceManager.GetString("intercept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empreinte structurelle : {0:F4} mégaoctets.
        /// </summary>
        internal static string intercept_accessibility {
            get {
                return ResourceManager.GetString("intercept_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude : {0:F6}.
        /// </summary>
        internal static string latitude {
            get {
                return ResourceManager.GetString("latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesures en temps réél.
        /// </summary>
        internal static string liveMetricsSection {
            get {
                return ResourceManager.GetString("liveMetricsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude : {0:F6}.
        /// </summary>
        internal static string longitude {
            get {
                return ResourceManager.GetString("longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructeur : {0}.
        /// </summary>
        internal static string manufacturer {
            get {
                return ResourceManager.GetString("manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le test mémoire est prêt.
        /// </summary>
        internal static string memoryTestReady_accessibility {
            get {
                return ResourceManager.GetString("memoryTestReady_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le test mémoire est en cours.
        /// </summary>
        internal static string memoryTestRunning_accessibility {
            get {
                return ResourceManager.GetString("memoryTestRunning_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test mémoire.
        /// </summary>
        internal static string memoryTestSection {
            get {
                return ResourceManager.GetString("memoryTestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section concernant les tests mémoire.
        /// </summary>
        internal static string memoryTestSection_accessibility {
            get {
                return ResourceManager.GetString("memoryTestSection_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle : {0}.
        /// </summary>
        internal static string model {
            get {
                return ResourceManager.GetString("model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version de l&apos;OS : {0}.
        /// </summary>
        internal static string osVersion {
            get {
                return ResourceManager.GetString("osVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string performanceTitle {
            get {
                return ResourceManager.GetString("performanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu : {0}.
        /// </summary>
        internal static string qrAlertContent {
            get {
                return ResourceManager.GetString("qrAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string qrAlertDismiss {
            get {
                return ResourceManager.GetString("qrAlertDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code scanné.
        /// </summary>
        internal static string qrAlertTitle {
            get {
                return ResourceManager.GetString("qrAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        internal static string qrTitle {
            get {
                return ResourceManager.GetString("qrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer 10 cribles d&apos;ératosthène.
        /// </summary>
        internal static string runCpuTest {
            get {
                return ResourceManager.GetString("runCpuTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer le test mémoire.
        /// </summary>
        internal static string runMemoryTest {
            get {
                return ResourceManager.GetString("runMemoryTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut : Prêt.
        /// </summary>
        internal static string testReady {
            get {
                return ResourceManager.GetString("testReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut : En cours....
        /// </summary>
        internal static string testRunning {
            get {
                return ResourceManager.GetString("testRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test UI.
        /// </summary>
        internal static string uiTestSection {
            get {
                return ResourceManager.GetString("uiTestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section concernant les tests UI.
        /// </summary>
        internal static string uiTestSection_accessibility {
            get {
                return ResourceManager.GetString("uiTestSection_accessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volatilité (RMSE) : {0:F4} MB.
        /// </summary>
        internal static string volatility {
            get {
                return ResourceManager.GetString("volatility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volatilité (RMSE) : {0:F4} mégaoctets.
        /// </summary>
        internal static string volatility_accessibility {
            get {
                return ResourceManager.GetString("volatility_accessibility", resourceCulture);
            }
        }
    }
}
